### ISSUE TITLE
Port DeepEnds to VS2017

### ISSUE THREAD

**Issue by 4sily** [zebmason/DeepEnds#3]
As a user, I'm happy that I can finally use Visual Studio 2017 for development.
However, now I have to keep VS2015 just to be able to use DeepEnds.
That is inconvenient, therefore I suggest to make it available for VS2017.

**Comment by zebmason** [comment]
You don't need to keep VS2015, you can use the console application. If you need to repeat the output to the VS console then use https://github.com/zebmason/Parrot or the binary from https://marketplace.visualstudio.com/items?itemName=ZebM.Parrot
